name: Build (Dev)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.24.2]
        node-version: [22.x]
    name: Dev Build ${{ matrix.go-version }} - ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Build frontend
        run: |
          cd web
          pnpm install
          pnpm build
          cd ..
          mkdir -p cmd/static
          cp -r web/build/* cmd/static/

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build backend
        run: |
          go build -ldflags "-X main.version=dev" -o magic-log ./cmd

      - name: Run go vet
        run: go vet ./...

      - name: Run go fmt check
        run: test -z "$(gofmt -l .)" || (echo "Please run gofmt" && exit 1)

      - name: Run unit tests
        run: go test ./...
