name: Build & Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     goos: [linux, darwin, windows]
    #     goarch: [amd64, arm64]
    # strategy:
    #   matrix:
    #     include:
    #       - goos: linux
    #         goarch: amd64
    #       # - goos: linux
    #       #   goarch: arm64
    #       # - goos: windows
    #       #   goarch: amd64
    strategy:
      matrix:
        go-version: [1.24.2]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22.x]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Build frontend
        run: |
          cd web
          pnpm install
          pnpm build
          cd ..
          mkdir -p cmd/static
          cp -r web/build/* cmd/static/

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build backend
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -ldflags "-X main.version=${{ github.ref_name }}" -o magic-log-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: magic-log-${{ matrix.goos }}-${{ matrix.goarch }}
          path: magic-log-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: magic-log-*/magic-log-*
