name: Build & Release

on:
  push:
    tags:
      - 'v*'
    # branches:
    #   - main
    #   - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux-amd64
            goos: linux
            goarch: amd64
            platform: ubuntu-latest
            go-version: 1.24.2
            node-version: 22.x
            ext: ""
          - name: darwin-arm64
            goos: darwin
            goarch: arm64
            platform: macos-latest
            go-version: 1.24.2
            node-version: 22.x
            ext: ""
          # - name: windows-amd64
          #   goos: windows
          #   goarch: amd64
          #   platform: windows-latest
          #   go-version: 1.24.2
          #   node-version: 22.x
          #   ext: ".exe"
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Build frontend
        run: |
          cd web
          pnpm install
          pnpm build
          cd ..
          mkdir -p cmd/static
          cp -r web/build/* cmd/static/

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build backend
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -ldflags "-X main.version=${{ github.ref_name }}" -o magic-log-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} ./cmd

      - name: Archive binary
        run: |
          tar -czf magic-log-${{ matrix.name }}.tar.gz magic-log-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}

      - name: Generate checksum
        run: |
          shasum -a 256 magic-log-${{ matrix.name }}.tar.gz > magic-log-${{ matrix.name }}.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: magic-log-${{ matrix.name }}
          path: magic-log-${{ matrix.name }}.tar.gz

      - name: Upload checksum
        uses: actions/upload-artifact@v4
        with:
          name: magic-log-${{ matrix.name }}.sha256
          path: magic-log-${{ matrix.name }}.sha256

  release:
    name: GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate checksum
        run: |
          shasum -a 256 magic-log-* > checksum.txt

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            checksum.txt
            magic-log-*/magic-log-*
